# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Digital_phantom2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1154, 622)
        MainWindow.setStyleSheet("background-color:rgb(240, 230, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 521, 561))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ernstAngle = QtWidgets.QPushButton(self.tab)
        self.ernstAngle.setGeometry(QtCore.QRect(120, 420, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ernstAngle.setFont(font)
        self.ernstAngle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ernstAngle.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(60, 124, 166, 217), stop:1 rgba(255, 255, 255, 255))")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/MRIsimulation/shefaa/search-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ernstAngle.setIcon(icon)
        self.ernstAngle.setIconSize(QtCore.QSize(35, 35))
        self.ernstAngle.setObjectName("ernstAngle")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PhantomShape = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PhantomShape.sizePolicy().hasHeightForWidth())
        self.PhantomShape.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PhantomShape.setFont(font)
        self.PhantomShape.setStyleSheet("background-color:rgb(197, 197, 255)")
        self.PhantomShape.setObjectName("PhantomShape")
        self.PhantomShape.addItem("")
        self.PhantomShape.addItem("")
        self.PhantomShape.addItem("")
        self.PhantomShape.addItem("")
        self.verticalLayout_3.addWidget(self.PhantomShape)
        self.PhantomSize = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PhantomSize.setFont(font)
        self.PhantomSize.setStyleSheet("background-color:rgb(197, 197, 255)")
        self.PhantomSize.setObjectName("PhantomSize")
        self.PhantomSize.addItem("")
        self.PhantomSize.addItem("")
        self.PhantomSize.addItem("")
        self.PhantomSize.addItem("")
        self.PhantomSize.addItem("")
        self.PhantomSize.addItem("")
        self.PhantomSize.addItem("")
        self.PhantomSize.addItem("")
        self.verticalLayout_3.addWidget(self.PhantomSize)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.browse = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.browse.setFont(font)
        self.browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(60, 124, 166, 217), stop:1 rgba(255, 255, 255, 255))")
        self.browse.setIcon(icon)
        self.browse.setIconSize(QtCore.QSize(35, 35))
        self.browse.setObjectName("browse")
        self.verticalLayout_4.addWidget(self.browse)
        self.createPhantom = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.createPhantom.setFont(font)
        self.createPhantom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createPhantom.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(60, 124, 166, 217), stop:1 rgba(255, 255, 255, 255))")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../.designer/MRIsimulation/shefaa/img_172965.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createPhantom.setIcon(icon1)
        self.createPhantom.setIconSize(QtCore.QSize(35, 35))
        self.createPhantom.setAutoDefault(False)
        self.createPhantom.setDefault(False)
        self.createPhantom.setFlat(False)
        self.createPhantom.setObjectName("createPhantom")
        self.verticalLayout_4.addWidget(self.createPhantom)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.AcquisionGraph = PlotWidget(self.tab)
        self.AcquisionGraph.setGeometry(QtCore.QRect(165, 151, 311, 251))
        self.AcquisionGraph.setStyleSheet("background-color:rgb(227, 222, 255)\n"
"")
        self.AcquisionGraph.setObjectName("AcquisionGraph")
        self.preparationGraph = PlotWidget(self.tab)
        self.preparationGraph.setGeometry(QtCore.QRect(10, 150, 151, 251))
        self.preparationGraph.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.preparationGraph.setObjectName("preparationGraph")
        self.maxErnstAngl = QtWidgets.QPushButton(self.tab)
        self.maxErnstAngl.setGeometry(QtCore.QRect(30, 490, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.maxErnstAngl.setFont(font)
        self.maxErnstAngl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maxErnstAngl.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(60, 124, 166, 217), stop:1 rgba(255, 255, 255, 255))")
        self.maxErnstAngl.setIcon(icon)
        self.maxErnstAngl.setIconSize(QtCore.QSize(35, 35))
        self.maxErnstAngl.setObjectName("maxErnstAngl")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(290, 490, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_3.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.T2 = PlotWidget(self.tab_2)
        self.T2.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.T2.setObjectName("T2")
        self.gridLayout_3.addWidget(self.T2, 3, 1, 1, 1)
        self.T1 = PlotWidget(self.tab_2)
        self.T1.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.T1.setObjectName("T1")
        self.gridLayout_3.addWidget(self.T1, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.time_span = QtWidgets.QSpinBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.time_span.setFont(font)
        self.time_span.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.time_span.setMaximum(2000)
        self.time_span.setProperty("value", 1000)
        self.time_span.setObjectName("time_span")
        self.gridLayout_3.addWidget(self.time_span, 6, 1, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 10, 381, 531))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StartUpCycle_2 = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.StartUpCycle_2.setFont(font)
        self.StartUpCycle_2.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.StartUpCycle_2.setMaximum(100)
        self.StartUpCycle_2.setProperty("value", 0)
        self.StartUpCycle_2.setObjectName("StartUpCycle_2")
        self.verticalLayout.addWidget(self.StartUpCycle_2)
        self.Artifacts = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Artifacts.setFont(font)
        self.Artifacts.setStyleSheet("background-color:rgb(197, 197, 255)\n"
"")
        self.Artifacts.setObjectName("Artifacts")
        self.Artifacts.addItem("")
        self.Artifacts.addItem("")
        self.Artifacts.addItem("")
        self.Artifacts.addItem("")
        self.verticalLayout.addWidget(self.Artifacts)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(64, 64))
        self.label_2.setStyleSheet("background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.0497512 rgba(60, 124, 166, 217), stop:0.631841 rgba(191, 189, 193, 245))")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(64, 64))
        self.label_3.setStyleSheet("background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.0497512 rgba(60, 124, 166, 217), stop:0.631841 rgba(191, 189, 193, 245))")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.start = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(60, 124, 166, 217), stop:1 rgba(255, 255, 255, 255))")
        self.start.setObjectName("start")
        self.verticalLayout.addWidget(self.start)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 0, 441, 551))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Zoom = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zoom.sizePolicy().hasHeightForWidth())
        self.Zoom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Zoom.setFont(font)
        self.Zoom.setStyleSheet("background-color:rgb(197, 197, 255)\n"
"")
        self.Zoom.setObjectName("Zoom")
        self.Zoom.addItem("")
        self.Zoom.addItem("")
        self.Zoom.addItem("")
        self.verticalLayout_5.addWidget(self.Zoom)
        self.graphicsView_Image = QtWidgets.QGraphicsView(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_Image.sizePolicy().hasHeightForWidth())
        self.graphicsView_Image.setSizePolicy(sizePolicy)
        self.graphicsView_Image.setStyleSheet("background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.0497512 rgba(60, 124, 166, 217), stop:0.631841 rgba(191, 189, 193, 245))")
        self.graphicsView_Image.setObjectName("graphicsView_Image")
        self.verticalLayout_5.addWidget(self.graphicsView_Image)
        self.graphicsView_Phantom = QtWidgets.QGraphicsView(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_Phantom.sizePolicy().hasHeightForWidth())
        self.graphicsView_Phantom.setSizePolicy(sizePolicy)
        self.graphicsView_Phantom.setStyleSheet("background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.0497512 rgba(60, 124, 166, 217), stop:0.631841 rgba(191, 189, 193, 245))")
        self.graphicsView_Phantom.setObjectName("graphicsView_Phantom")
        self.verticalLayout_5.addWidget(self.graphicsView_Phantom)
        self.tabWidget.addTab(self.tab_3, "")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelT1 = QtWidgets.QLabel(self.centralwidget)
        self.labelT1.setGeometry(QtCore.QRect(540, 140, 271, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelT1.sizePolicy().hasHeightForWidth())
        self.labelT1.setSizePolicy(sizePolicy)
        self.labelT1.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.labelT1.setStyleSheet("background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.0497512 rgba(60, 124, 166, 217), stop:0.631841 rgba(191, 189, 193, 245))")
        self.labelT1.setFrameShape(QtWidgets.QFrame.Box)
        self.labelT1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelT1.setLineWidth(3)
        self.labelT1.setMidLineWidth(0)
        self.labelT1.setText("")
        self.labelT1.setTextFormat(QtCore.Qt.AutoText)
        self.labelT1.setScaledContents(True)
        self.labelT1.setObjectName("labelT1")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(630, 350, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.LabelT2 = QtWidgets.QLabel(self.centralwidget)
        self.LabelT2.setGeometry(QtCore.QRect(540, 380, 271, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelT2.sizePolicy().hasHeightForWidth())
        self.LabelT2.setSizePolicy(sizePolicy)
        self.LabelT2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.LabelT2.setStyleSheet("background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.0497512 rgba(60, 124, 166, 217), stop:0.631841 rgba(191, 189, 193, 245))")
        self.LabelT2.setFrameShape(QtWidgets.QFrame.Box)
        self.LabelT2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LabelT2.setLineWidth(3)
        self.LabelT2.setMidLineWidth(0)
        self.LabelT2.setText("")
        self.LabelT2.setTextFormat(QtCore.Qt.AutoText)
        self.LabelT2.setScaledContents(True)
        self.LabelT2.setObjectName("LabelT2")
        self.plainTextEdit1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit1.setGeometry(QtCore.QRect(630, 110, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit1.sizePolicy().hasHeightForWidth())
        self.plainTextEdit1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit1.setFont(font)
        self.plainTextEdit1.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.plainTextEdit1.setObjectName("plainTextEdit1")
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(540, 10, 291, 91))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Preb = QtWidgets.QComboBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Preb.setFont(font)
        self.Preb.setStyleSheet("background-color:rgb(197, 197, 255)")
        self.Preb.setObjectName("Preb")
        self.Preb.addItem("")
        self.Preb.addItem("")
        self.Preb.addItem("")
        self.Preb.addItem("")
        self.Preb.addItem("")
        self.horizontalLayout.addWidget(self.Preb)
        self.aquise = QtWidgets.QComboBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.aquise.setFont(font)
        self.aquise.setStyleSheet("background-color:rgb(197, 197, 255)")
        self.aquise.setObjectName("aquise")
        self.aquise.addItem("")
        self.aquise.addItem("")
        self.aquise.addItem("")
        self.aquise.addItem("")
        self.aquise.addItem("")
        self.aquise.setItemText(4, "")
        self.horizontalLayout.addWidget(self.aquise)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(840, 10, 301, 561))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color:\n"
"rgb(215, 218, 255)")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.label = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label.setStyleSheet("background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.0497512 rgba(60, 124, 166, 217), stop:0.631841 rgba(191, 189, 193, 245))")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(3)
        self.label.setMidLineWidth(0)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.FA = QtWidgets.QSpinBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FA.setFont(font)
        self.FA.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.FA.setMaximum(360)
        self.FA.setSingleStep(0)
        self.FA.setProperty("value", 90)
        self.FA.setObjectName("FA")
        self.verticalLayout_2.addWidget(self.FA)
        self.TR = QtWidgets.QSpinBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TR.setFont(font)
        self.TR.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.TR.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.TR.setMaximum(20000)
        self.TR.setSingleStep(0)
        self.TR.setProperty("value", 1000)
        self.TR.setDisplayIntegerBase(10)
        self.TR.setObjectName("TR")
        self.verticalLayout_2.addWidget(self.TR)
        self.TE = QtWidgets.QSpinBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TE.setFont(font)
        self.TE.setStyleSheet("background-color:rgb(227, 222, 255)")
        self.TE.setSuffix("")
        self.TE.setMaximum(2000)
        self.TE.setSingleStep(0)
        self.TE.setProperty("value", 400)
        self.TE.setObjectName("TE")
        self.verticalLayout_2.addWidget(self.TE)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1154, 20))
        self.menubar.setObjectName("menubar")
        self.menuShepp_Logan_phantom_and_features = QtWidgets.QMenu(self.menubar)
        self.menuShepp_Logan_phantom_and_features.setTearOffEnabled(False)
        self.menuShepp_Logan_phantom_and_features.setSeparatorsCollapsible(False)
        self.menuShepp_Logan_phantom_and_features.setToolTipsVisible(False)
        self.menuShepp_Logan_phantom_and_features.setObjectName("menuShepp_Logan_phantom_and_features")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuShepp_Logan_phantom_and_features.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ernstAngle.setText(_translate("MainWindow", "Draw Ernst Angle"))
        self.PhantomShape.setItemText(0, _translate("MainWindow", "Phantom shape:"))
        self.PhantomShape.setItemText(1, _translate("MainWindow", "Shepp-Logan"))
        self.PhantomShape.setItemText(2, _translate("MainWindow", "Phantom 1"))
        self.PhantomShape.setItemText(3, _translate("MainWindow", "phantom 2"))
        self.PhantomSize.setCurrentText(_translate("MainWindow", "Phantom size:"))
        self.PhantomSize.setItemText(0, _translate("MainWindow", "Phantom size:"))
        self.PhantomSize.setItemText(1, _translate("MainWindow", "9"))
        self.PhantomSize.setItemText(2, _translate("MainWindow", "20"))
        self.PhantomSize.setItemText(3, _translate("MainWindow", "32"))
        self.PhantomSize.setItemText(4, _translate("MainWindow", "64"))
        self.PhantomSize.setItemText(5, _translate("MainWindow", "128"))
        self.PhantomSize.setItemText(6, _translate("MainWindow", "256"))
        self.PhantomSize.setItemText(7, _translate("MainWindow", "512"))
        self.browse.setText(_translate("MainWindow", "Browse Phantom"))
        self.createPhantom.setText(_translate("MainWindow", "Create Phantom"))
        self.maxErnstAngl.setText(_translate("MainWindow", "Max Ernst Angle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.time_span.setPrefix(_translate("MainWindow", "t = "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Graphs"))
        self.StartUpCycle_2.setPrefix(_translate("MainWindow", "Start Up Cycle = "))
        self.Artifacts.setCurrentText(_translate("MainWindow", "Artifacts:"))
        self.Artifacts.setItemText(0, _translate("MainWindow", "Artifacts:"))
        self.Artifacts.setItemText(1, _translate("MainWindow", "Normal"))
        self.Artifacts.setItemText(2, _translate("MainWindow", "Aliasing"))
        self.Artifacts.setItemText(3, _translate("MainWindow", "ImproperSampling"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "K-space"))
        self.Zoom.setItemText(0, _translate("MainWindow", "Zoom:"))
        self.Zoom.setItemText(1, _translate("MainWindow", "Linked"))
        self.Zoom.setItemText(2, _translate("MainWindow", "NonLinked"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Zoom"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "T2 Image"))
        self.plainTextEdit1.setPlainText(_translate("MainWindow", "T1 Image"))
        self.Preb.setCurrentText(_translate("MainWindow", "Preparation:"))
        self.Preb.setItemText(0, _translate("MainWindow", "Preparation:"))
        self.Preb.setItemText(1, _translate("MainWindow", "NoPreb"))
        self.Preb.setItemText(2, _translate("MainWindow", "T1IR"))
        self.Preb.setItemText(3, _translate("MainWindow", "T2Preb"))
        self.Preb.setItemText(4, _translate("MainWindow", "Tagging"))
        self.aquise.setCurrentText(_translate("MainWindow", "Acquisition:"))
        self.aquise.setItemText(0, _translate("MainWindow", "Acquisition:"))
        self.aquise.setItemText(1, _translate("MainWindow", "SSFP"))
        self.aquise.setItemText(2, _translate("MainWindow", "SpinEcho"))
        self.aquise.setItemText(3, _translate("MainWindow", "GRE"))
        self.FA.setPrefix(_translate("MainWindow", "FA = "))
        self.TR.setPrefix(_translate("MainWindow", "TR = "))
        self.TE.setPrefix(_translate("MainWindow", "TE = "))
        self.menuShepp_Logan_phantom_and_features.setTitle(_translate("MainWindow", "Different MRI Phantoms"))

from pyqtgraph import PlotWidget
